# Generated by Django 5.0 on 2026-04-12 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='always_know',
            field=models.TextField(blank=True, help_text='What the AI should ALWAYS know'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='doc_1',
            field=models.FileField(blank=True, null=True, upload_to='ai_docs/'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='doc_2',
            field=models.FileField(blank=True, null=True, upload_to='ai_docs/'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='doc_3',
            field=models.FileField(blank=True, null=True, upload_to='ai_docs/'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='policies',
            field=models.TextField(blank=True, help_text='Important policies'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='pricing_rules',
            field=models.TextField(blank=True, help_text='Pricing rules'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'E-commerce / Online Store'), ('school', 'School / Educational Institution'), ('clinic', 'Clinic / Hospital'), ('service', 'Service Business'), ('hotel', 'Hotel / Hospitality'), ('restaurant', 'Restaurant / Food Business'), ('finance', 'Finance / Fintech'), ('corporate', 'Corporate / Company'), ('coaching', 'Coaching / Course Creator'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='business_type',
            field=models.CharField(blank=True, choices=[('ecommerce', 'E-commerce / Online Store'), ('school', 'School / Educational Institution'), ('clinic', 'Clinic / Hospital'), ('service', 'Service Business'), ('hotel', 'Hotel / Hospitality'), ('restaurant', 'Restaurant / Food Business'), ('finance', 'Finance / Fintech'), ('corporate', 'Corporate / Company'), ('coaching', 'Coaching / Course Creator'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.TextField(blank=True, help_text='Comma-separated variants e.g. Red, Blue, Size M'),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('emergency_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('availability', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='App.clinicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='App.clinicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GenericServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerings', models.TextField(blank=True, help_text='What you offer (free text)')),
                ('pricing_summary', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generic_service_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.CharField(blank=True, max_length=20)),
                ('check_out_time', models.CharField(blank=True, max_length=20)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated: WiFi, Pool, Gym…')),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='App.hotelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.TextField(blank=True)),
                ('delivery_option', models.CharField(choices=[('dine_only', 'Dine-in Only'), ('delivery_only', 'Delivery Only'), ('both', 'Dine-in & Delivery'), ('takeaway', 'Takeaway')], default='both', max_length=20)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_order', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='e.g. Starters, Mains, Drinks', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='App.restaurantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_offered', models.TextField(blank=True, help_text='e.g. JSS1, JSS2, SS1, SS2, SS3')),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('term_structure', models.CharField(blank=True, help_text='e.g. 3 terms per year', max_length=50)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hostel_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_fees', models.TextField(blank=True)),
                ('term_1_start', models.DateField(blank=True, null=True)),
                ('term_1_end', models.DateField(blank=True, null=True)),
                ('term_2_start', models.DateField(blank=True, null=True)),
                ('term_2_end', models.DateField(blank=True, null=True)),
                ('term_3_start', models.DateField(blank=True, null=True)),
                ('term_3_end', models.DateField(blank=True, null=True)),
                ('exam_period', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_required', models.BooleanField(default=True)),
                ('booking_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('custom', 'Custom Quote'), ('hourly', 'Per Hour')], default='fixed', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time', models.CharField(blank=True, max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='App.servicebusiness')),
            ],
        ),
    ]
